//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlaRecursos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pessoa_Recurso
    {
        public int pessoa_recurso_id { get; set; }
        public int pessoa_id { get; set; }
        public int recurso_id { get; set; }
        public string valor { get; set; }
        public Nullable<System.DateTime> data_inicio { get; set; }
        public Nullable<System.DateTime> data_termino { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }
        public virtual Recurso Recurso { get; set; }
    }
}
